export const loginCredentials = {
  email: "admin@gmail.com",
  password: "123",
  status: true,
  role: "admin",
  message: "login successfully",
  token: "1164|ihHvE9J6cn1U3St4Sk6v6JKOdm2ARA87hXYbIdS63831040a",
};
export const loggedInUser = {
  "user-id": 1,
  "full-name": "Arthur Morgan",
  "first-name": "Arthur",
  "last-name": "Morgan",
  type: "admin",
  token: "somerandomtokenwhichis38characterslong",
  phone: "+190078601",
  dialing_code: "+1",
  email: "arthurmorgan@rdr2.com",
  "photo-path": "https://static.wikia.nocookie.net/villains/images/8/8d/Red_Dead_2_Arthur_Morgan_Promotional_Portrait_1.png",
};
export const notifications = [
  {
    id: 1,
    user: {
      name: "Emily Clark",
      "profile-image": "https://t3.ftcdn.net/jpg/06/92/98/26/360_F_692982616_sFOE56exqjylP20296OjiD83FQxewdDw.jpg",
    },
    action: "liked your comment",
    notificationText: `John reported an issue: "Unable to create a new football discussion group."`,
    timestamp: "5 minutes ago",
    date: "08/19/2024",
    read: true,
  },
  {
    id: 2,
    user: {
      name: "John Doe",
      "profile-image": "https://t3.ftcdn.net/jpg/06/92/98/26/360_F_692982616_sFOE56exqjylP20296OjiD83FQxewdDw.jpg",
    },
    action: "shared your post",
    notificationText: `Alex raised a query: "Posted football tactics, but it doesn’t show in the group."`,
    timestamp: "3 hours ago",
    date: "08/19/2024",
    read: false,
  },
  {
    id: 3,
    user: {
      name: "Sophia Brown",
      "profile-image": "https://t3.ftcdn.net/jpg/06/92/98/26/360_F_692982616_sFOE56exqjylP20296OjiD83FQxewdDw.jpg",
    },
    action: "commented on your photo and this text is here just to make the notification very long",
    notificationText: `Chris submitted a complaint: "Messages not sending in the group chat."`,
    timestamp: "10 minutes ago",
    date: "08/19/2024",
    read: true,
  },
  {
    id: 4,
    user: {
      name: "David Wilson",
      "profile-image": "https://t3.ftcdn.net/jpg/06/92/98/26/360_F_692982616_sFOE56exqjylP20296OjiD83FQxewdDw.jpg",
    },
    action: "followed you",
    notificationText: `Andrew encountered a problem: "Trying to join a football analysis group but getting an error."`,
    timestamp: "1 day ago",
    date: "08/18/2024",
    read: false,
  },
  {
    id: 5,
    user: {
      name: "Olivia Johnson",
      "profile-image": "https://t3.ftcdn.net/jpg/06/92/98/26/360_F_692982616_sFOE56exqjylP20296OjiD83FQxewdDw.jpg",
    },
    action: "added your post to favorites",
    notificationText: `James flagged an issue: "Football post content gets flagged for no reason."`,
    timestamp: "30 minutes ago",
    date: "08/19/2024",
    read: true,
  },
];

export const NewUsers = [
  { id: 1, newUsers: 15 },
  { id: 2, newUsers: 13 },
  { id: 3, newUsers: 15 },
  { id: 4, newUsers: 21 },
  { id: 5, newUsers: 23 },
  { id: 6, newUsers: 18 },
  { id: 7, newUsers: 18 },
  { id: 8, newUsers: 23 },
  { id: 9, newUsers: 25 },
  { id: 10, newUsers: 20 },
  { id: 11, newUsers: 26 },
  { id: 12, newUsers: 28 },
];

export const userManagementData = [
  {
    id: "1",
    name: "John Doe",
    email: "johndoe@email.com",
    registeredDate: "mm/dd/yyyy",
    status: "active",
  },
  {
    id: "2",
    name: "Arthur Morgan",
    email: "arthurmorgan@rdr.com",
    registeredDate: "mm/dd/yyyy",
    status: "active",
  },
  {
    id: "3",
    name: "Chris Evan",
    email: "chrisevan@captainamerica.com",
    registeredDate: "mm/dd/yyyy",
    status: "inactive",
  },
  {
    id: "4",
    name: "Alan Wake",
    email: "Alanwake@alanwake.com",
    registeredDate: "mm/dd/yyyy",
    status: "active",
  },
  {
    id: "5",
    name: "Captain Price",
    email: "captainprice@cod.com",
    registeredDate: "mm/dd/yyyy",
    status: "inactive",
  },
  {
    id: "6",
    name: "Nomad",
    email: "nomad@crysis.com",
    registeredDate: "mm/dd/yyyy",
    status: "inactive",
  },
  {
    id: "7",
    name: "Batman",
    email: "batman@dc.com",
    registeredDate: "mm/dd/yyyy",
    status: "active",
  },
  {
    id: "8",
    name: "Spiderman",
    email: "spiderman@marvel.com",
    registeredDate: "mm/dd/yyyy",
    status: "inactive",
  },
];
export const userDetails = [
  {
    id: "1",
    name: "John Doe",
    email: "johndoe@emil.com",
    phone: "+190078601",
    address: "House no 23, Johny street",
    registeredDate: "mm/dd/yyyy",
    image: "https://capecoraltech.edu/wp-content/uploads/2016/01/tutor-8-3.jpg",
    status: "active",
    orders: ["123", "124", "125", "126", "127"],
    commisions: ["223", "224", "225", "226", "227"],
    newsfeed: "1234",
  },
  {
    id: "2",
    name: "arthur Morgan",
    email: "arthurmorgan@rdr2.com",
    phone: "+34 958 151 271",
    address: "Red dead redemption",
    registeredDate: "mm/dd/yyyy",
    image: "https://static.wikia.nocookie.net/reddeadredemption/images/5/52/RDR2_Arthur_Morgan_Default.jpg",
    status: "active",
    orders: ["123", "124", "125", "126", "127"],
    commisions: ["223", "224", "225", "226", "227"],
    newsfeed: "1234",
  },
  {
    id: "3",
    name: "Chris Evan",
    email: "chrisevan@captainamerica.com",
    phone: "+54 875 288 7012",
    address: "Avengers",
    registeredDate: "mm/dd/yyyy",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDFklWjdBJoveiwsy2k6_tjFAGxX9NRLkXOA&s",
    status: "inactive",
    orders: ["123", "124", "125", "126", "127"],
    commisions: ["223", "224", "225", "226", "227"],
    newsfeed: "1234",
  },
  {
    id: "4",
    name: "Alan Wake",
    email: "alanwake@alanwakeII.com",
    phone: "+1-857-239-7601",
    address: "Dark Place, NY",
    registeredDate: "mm/dd/yyyy",
    image: "https://assetsio.gnwcdn.com/WAKE2-SITE.jpg?width=1200&height=1200&fit=crop&quality=100&format=png&enable=upscale&auto=webp",
    status: "active",
    orders: ["123", "124", "125", "126", "127"],
    commisions: ["223", "224", "225", "226", "227"],
    newsfeed: "1234",
  },
  {
    id: "5",
    name: "Captain Price",
    email: "price@callofduty.com",
    phone: "+974 5320 9120",
    address: "Call of Duty 4, Modern Warfare",
    registeredDate: "mm/dd/yyyy",
    image:
      "https://staticg.sportskeeda.com/editor/2023/07/62a01-16907107416585-1920.jpg?w=640",
    status: "inactive",
    orders: ["123", "124", "125", "126", "127"],
    commisions: ["223", "224", "225", "226", "227"],
    newsfeed: "1234",
  },
];
// MileStone Design
// https://www.figma.com/design/WSDIXs1BdGilcQZJ32S7JY/Milestone---Project?node-id=487-83339&t=dgprVwnzibfJkq4A-1

// Updated
// https://www.figma.com/design/zpHb1r9gkFPu3K95m686Bk/Milestone---Project?node-id=1-8333&t=q9LMySj8QwRsAwbj-1